Update mdata-get
Makes all error output go to FD2, so that `root_authorized_keys`, if not present, won't create a `~root/.ssh/authorized_keys` file with an error message in it.

diff --git a/src/linux/lib/smartdc/mdata-get b/src/linux/lib/smartdc/mdata-get
--- a/src/linux/lib/smartdc/mdata-get
+++ b/src/linux/lib/smartdc/mdata-get
@@ -72,10 +72,10 @@ while [[ ${keep_trying} -eq 1 ]]; do
   fi
 
   if [[ ${status} == "NOTFOUND" ]]; then
-    echo "No metadata for ${key}"
+    echo "No metadata for ${key}" >&2
     exit 1
   elif [[ ${status} != "SUCCESS" ]]; then
-    echo "Error getting metadata for key ${key}: ${status}"
+    echo "Error getting metadata for key ${key}: ${status}" >&2
     exit 2
   fi
 
